services:
  arm:
    build: .
    working_dir: /app
    environment:
      YOLO_CONFIG_DIR: /app/.config/Ultralytics
    volumes:
      - ./:/app
      - yolo_weights:/app/.cache/ultralytics
    command: ["python", "/app/dockertest/Arm.py"]

volumes:
  yolo_weights: {}